steps:
- name: maven:3.6-jdk-8-slim
  entrypoint: 'mvn'
  args: ['package', '-Dmaven.test.skip=true', '-P', 'embedded-jetty', '-Dlogback.configuration.file=src/main/docker/logback.xml']
- name: docker
  args: ['build', '-f', 'src/main/docker/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/dependency-track', '-t', 'gcr.io/$PROJECT_ID/dependency-track:latest', '.']
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', 'dependency-track', '--namespace', 'dtrack', './dependency-track-helm']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=eu-west2-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=dtrack-prod-cluster'
    - 'TILLERLESS=true'
    - 'TILLER_NAMESPACE=test'
images: ['gcr.io/$PROJECT_ID/dependency-track']
