apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/appthreat/dependency-track
  local:
    useDockerCLI: true
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: dependency-track
      chartPath: dependency-track-helm
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image: gcr.io/appthreat/dependency-track
