{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "dependency-track.fullname" . }}
  labels:
    app: "{{ template "dependency-track.fullname" . }}"
    chart: "{{ template "dependency-track.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "dependency-track.storageClass" . }}
{{- end -}}
