name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '1.8.0', '11.0.x' ]
    env:
      DOCKER_REPO: owasp/dependency-track
      DOCKER_TAG: snapshot
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: |
          mvn clean package -Dmaven.test.skip=true -P embedded-jetty -Dlogback.configuration.file=src/main/docker/logback.xml
      - name: SAST scanning
        uses: appthreat/sast-scan-action@master
        with:
          type: "java"
      - name: debug
        run: |
          ls -lh ${GITHUB_HOME}/reports
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: reports
          path: ${GITHUB_HOME}/reports
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: dependency-track
          # Directory containing files to upload
          path: target/dependency-track-embedded.war
